import Head from "next/head";
import styles from "@/styles/Gallery.module.css";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Avatars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Gallery />
      </main>
    </>
  );
}

function Adder(props: { onAdderClick: () => void }) {
  return (
    <button className={`${styles.tile} ${styles.adder}`} onClick={props.onAdderClick}>
      <Image
        src="/add.svg"
        width={70}
        height={70}
        alt="add sign"
      />
    </button>
  );
}

interface Avatar {
  id: number;
  url: string;
}

function Gallery() {
  const [avatars, setAvatars] = useState(new Array<Avatar>(0));

  async function handleAdderClick() {
    try {
      const res = await fetch('https://tinyfac.es/api/data?limit=1&quality=0');
      const data = await res.json();
      if (!data) {
        throw new Error('data cannot be parsed');
      }
      const avatar: Avatar = { id: data[0].id, url: data[0].url };
      setAvatars([...avatars, avatar]);
    } catch (e) {
      console.log('an error occured');
    }
  }

  return (
    <div className={styles.gallery}>
      {avatars.map((avatar) => 
        <Image
          src={avatar.url}
          width={240}
          height={240}
          alt="avatar"
          key={avatar.id}
          className={`${styles.avatar} ${styles.tile}`}
        />
      )}
      <Adder onAdderClick={handleAdderClick}/>
    </div>
  )
}
